edx_sysadmin/api/urls.py
"""
URLs for edx_sysadmin.
"""
from django.conf.urls import url, include

from edx_sysadmin.api.views import (
    GitCourseDetailsAPIView,
    GitReloadAPIView,
)

app_name = "api"

urlpatterns = [
    url("^gitreload/$", GitReloadAPIView.as_view(), name="git-reload"),
    url(
        "^gitcoursedetails/$",
        GitCourseDetailsAPIView.as_view(),
        name="git-course-details",
    ),
]

edx_sysadmin/urls.py
"""
URLs for edx_sysadmin.
"""
from django.conf.urls import url, include

from edx_sysadmin.views import (
    SysadminDashboardRedirectionView,
    CoursesPanel,
    UsersPanel,
    GitImport,
    GitLogs,
)

app_name = "sysadmin"


urlpatterns = [
    url("^$", SysadminDashboardRedirectionView.as_view(), name="sysadmin"),
    url(r"^courses/?$", CoursesPanel.as_view(), name="courses"),
    url(r"^gitimport/$", GitImport.as_view(), name="gitimport"),
    url(r"^gitlogs/?$", GitLogs.as_view(), name="gitlogs"),
    url(r"^gitlogs/(?P<course_id>.+)$", GitLogs.as_view(), name="gitlogs_detail"),
    url(r"^users/$", UsersPanel.as_view(), name="users"),
    url(r"^api/", include("edx_sysadmin.api.urls", namespace="api")),
]

edx_sysadmin/api/views.py
import json
import logging
from path import Path as path
import subprocess

from django.conf import settings
from django.utils.decorators import method_decorator
from django.utils.translation import gettext as _
from rest_framework import status, permissions
from rest_framework.authentication import SessionAuthentication
from rest_framework.views import APIView
from rest_framework.response import Response

from edx_sysadmin.api.permissions import GithubWebhookPermission
from edx_sysadmin.git_import import (
    add_repo,
    DEFAULT_GIT_REPO_DIR,
)
from edx_sysadmin.utils.utils import (
    get_local_active_branch,
    get_local_course_repo,
    get_clean_branch_name,
)

logger = logging.getLogger(__name__)


class GitReloadAPIView(APIView):
    """
    APIView to reload courses from github on triggering github webhook
    """

    permission_classes = [GithubWebhookPermission]

    def post(self, request):
        """
        Trigger for github webhooks for course reload
        """
        err_msg = ""
        try:
            event = request.headers.get("X-Github-Event")
            payload = json.loads(request.body)
            repo_ssh_url = payload["repository"].get("ssh_url")
            repo_name = payload["repository"].get("name")
            pushed_branch = payload.get("ref", "")
            clean_pushed_branch = get_clean_branch_name(pushed_branch)

            if not event == "push":
                err_msg = _("The API works for 'Push' events only")
            elif not repo_name:
                err_msg = _("Couldn't find Repo's name in the payload")
            elif not repo_ssh_url:
                err_msg = _("Couldn't find Repo's ssh_url in the payload")
            elif not pushed_branch:
                err_msg = _("Couldn't find Repo's pushed branch ref in the payload")
            elif (
                not hasattr(settings, "SYSADMIN_DEFAULT_BRANCH")
                or settings.SYSADMIN_DEFAULT_BRANCH is None
            ):
                err_msg = _("SYSADMIN_DEFAULT_BRANCH is not configured in settings")
            elif clean_pushed_branch != settings.SYSADMIN_DEFAULT_BRANCH:
                err_msg = _(
                    "Couldn't entertain reload request for the branch ({}), expected branch is ({}) "
                ).format(clean_pushed_branch, settings.SYSADMIN_DEFAULT_BRANCH)
            else:
                repo = get_local_course_repo(repo_name)
                if not repo:
                    # New course reload trigger received from a repo but we don't have it's local copy.
                    # So, We will do the course import instead of reload

                    add_repo.delay(
                        repo=repo_ssh_url, branch=settings.SYSADMIN_DEFAULT_BRANCH
                    )
                    msg = _(
                        "No local course copy found. Triggered course import from branch: {} of repo: {}"
                    ).format(settings.SYSADMIN_DEFAULT_BRANCH, repo_name)
                    return self.get_reload_response(
                        msg=msg, status_code=status.HTTP_200_OK
                    )

                else:
                    # We have an existing local copy of the course, so we will reload the course after making sure that
                    # the reload trigger is from the same branch that was used to import the course initially
                    active_branch = get_local_active_branch(repo)
                    if not active_branch or not active_branch == pushed_branch:
                        err_msg = _(
                            "The pushed branch ({}) is not currently in use"
                        ).format(pushed_branch)
                    else:
                        add_repo.delay(repo_ssh_url)
                        msg = _("Triggered reloading branch: {} of repo: {}").format(
                            active_branch, repo_name
                        )
                        return self.get_reload_response(
                            msg=msg, status_code=status.HTTP_200_OK
                        )

        except Exception as e:
            err_msg = str(e)

        return self.get_reload_response(
            msg=err_msg, status_code=status.HTTP_400_BAD_REQUEST
        )

    def get_reload_response(self, msg, status_code):
        if status_code == status.HTTP_200_OK:
            logger.info(f"{self.__class__.__name__}:: {msg}")
        else:
            logger.exception(f"{self.__class__.__name__}:: {msg}")

        return Response(
            {"message": msg},
            status=status_code,
        )


class GitCourseDetailsAPIView(APIView):
    """
    APIView to get git related details of list of courses
    """

    authentication_classes = [SessionAuthentication]
    permission_classes = [permissions.IsAdminUser]

    def get(self, request):
        """
        Get git related details of list of courses
        """
        try:
            course_dir = request.GET.get("courseDir")
            if course_dir:
                return Response(
                    self.git_info_for_course(course_dir),
                    status=status.HTTP_200_OK,
                )
            else:
                err_msg = "Course directory name is required"

        except Exception as e:
            err_msg = str(e)

        logger.exception(f"{self.__class__.__name__}:: {err_msg}")
        return Response(
            {"message": err_msg},
            status=status.HTTP_400_BAD_REQUEST,
        )

    def git_info_for_course(self, course_dir):
        """This pulls out some git info like the last commit"""

        git_dir = settings.DATA_DIR / course_dir

        # Try the data dir, then try to find it in the git import dir
        if not git_dir.exists():
            git_repo_dir = getattr(settings, "GIT_REPO_DIR", DEFAULT_GIT_REPO_DIR)
            git_dir = path(git_repo_dir) / course_dir
            if not git_dir.exists():
                return ["", "", ""]

        cmd = [
            "git",
            "log",
            "-1",
            '--format=format:{ "commit": "%H", "author": "%an %ae", "date": "%ad"}',
        ]
        try:
            output_json = json.loads(
                subprocess.check_output(cmd, cwd=git_dir).decode("utf-8")
            )
        except OSError as error:
            logger.warning("Error fetching git data: %s - %s", course_dir, error)
            raise
        except (ValueError, subprocess.CalledProcessError):
            raise

        return output_json

edx_sysadmin/views.py
"""
Views for the Open edX SysAdmin Plugin
"""
# pylint: disable=wrong-import-order
import logging
from io import StringIO

from common.djangoapps.student.roles import CourseInstructorRole
from django.contrib.auth.decorators import user_passes_test
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.http import Http404
from django.shortcuts import render
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.utils.html import escape
from django.utils.translation import gettext as _
from django.views.decorators.cache import cache_control
from django.views.decorators.csrf import ensure_csrf_cookie
from django.views.decorators.http import condition
from django.views.generic.base import RedirectView, TemplateView
from opaque_keys.edx.keys import CourseKey
from xmodule.modulestore.django import modulestore

from edx_sysadmin import git_import
from edx_sysadmin.forms import UserRegistrationForm
from edx_sysadmin.git_import import GitImportError
from edx_sysadmin.models import CourseGitLog
from edx_sysadmin.utils.markup import HTML, Text
from edx_sysadmin.utils.utils import (
    create_user_account,
    get_course_by_id,
    get_registration_required_extra_fields_with_values,
    is_registration_api_functional,
    user_has_access_to_courses_panel,
    user_has_access_to_git_import_panel,
    user_has_access_to_git_logs_panel,
    user_has_access_to_sysadmin,
    user_has_access_to_users_panel,
)

log = logging.getLogger(__name__)


@method_decorator(
    user_passes_test(
        user_has_access_to_sysadmin, login_url="/404", redirect_field_name=None
    ),
    name="dispatch",
)
class SysadminDashboardRedirectionView(RedirectView):
    """Redirection view to land user to specific panel"""

    def get_redirect_url(self, *args, **kwargs):
        """Override redirection_url"""

        if user_has_access_to_users_panel(self.request.user):
            return reverse("sysadmin:users")
        elif user_has_access_to_courses_panel(self.request.user):
            return reverse("sysadmin:courses")
        elif user_has_access_to_git_logs_panel(self.request.user):
            return reverse("sysadmin:gitlogs")
        elif user_has_access_to_git_import_panel(self.request.user):
            return reverse("sysadmin:gitimport")
        else:
            raise Http404


@method_decorator(ensure_csrf_cookie, name="dispatch")
@method_decorator(
    user_passes_test(
        user_has_access_to_sysadmin, login_url="/404", redirect_field_name=None
    ),
    name="dispatch",
)
@method_decorator(
    cache_control(no_cache=True, no_store=True, must_revalidate=True), name="dispatch"
)
@method_decorator(condition(etag_func=None), name="dispatch")
class SysadminDashboardBaseView(TemplateView):
    """Base view for SysAdmin Dashboard's Panels."""

    template_name = "edx_sysadmin/base.html"

    def get_context_data(self, **kwargs):
        """
        Overriding get_context_data method to add custom fields
        """
        context = super().get_context_data(**kwargs)
        context.update(
            {
                "show_users_tab": user_has_access_to_users_panel(self.request.user),
                "show_courses_tab": user_has_access_to_courses_panel(self.request.user),
                "show_git_logs_tab": user_has_access_to_git_logs_panel(
                    self.request.user
                ),
                "show_git_import_tab": user_has_access_to_git_import_panel(
                    self.request.user
                ),
            }
        )
        return context


@method_decorator(
    user_passes_test(
        user_has_access_to_courses_panel, login_url="/404", redirect_field_name=None
    ),
    name="dispatch",
)
class CoursesPanel(SysadminDashboardBaseView):
    """
    This manages deleting courses.
    """

    template_name = "edx_sysadmin/courses.html"
    datatable = []

    def get_course_summaries(self):
        """Get an iterable list of course summaries."""

        return modulestore().get_course_summaries()

    def make_datatable(self, courses=None):
        """Creates course information datatable"""

        data = {}
        for course in courses or self.get_course_summaries():
            data[course.id] = {
                "display_name": course.display_name,
                "course_id": course.id,
                "git_directory": course.id.course,
            }

        return dict(
            header=[
                _("Course Name"),
                _("Directory/ID"),
                # Translators: "Git Commit" is a computer command; see http://gitref.org/basic/#commit
                _("Git Commit"),
                _("Last Change"),
                _("Last Editor"),
                _("Action"),
            ],
            title=_("Information about all courses"),
            data=data,
            api_url=reverse("sysadmin:api:git-course-details"),
        )

    def get_context_data(self, **kwargs):
        """
        Overriding get_context_data method to add custom fields
        """
        context = super().get_context_data(**kwargs)
        context.update(
            {
                "is_courses_tab": True,
                "datatable": self.make_datatable(),
            }
        )
        return context

    def post(self, request):
        """Handle delete action from courses view"""

        action = request.POST.get("action", "")
        message = ""
        if action == "del_course":
            course_id = request.POST.get("course_id", "").strip()
            course_key = CourseKey.from_string(course_id)
            course_found = False
            try:
                course = get_course_by_id(course_key)
                course_found = True
            except Exception as err:  # pylint: disable=broad-except
                message += Text(
                    _(
                        "{div_start} Error - cannot get course with ID {course_key} {error} {div_end}"
                    )
                ).format(
                    div_start=HTML("<div class='error'>"),
                    course_key=course_key,
                    error=HTML("<br/><pre>{error}</pre>").format(
                        error=escape(str(err))
                    ),
                    div_end=HTML("</div>"),
                )

            if course_found:
                # delete course that is stored with mongodb backend
                modulestore().delete_course(course.id, request.user.id)
                # don't delete user permission groups, though
                message += Text(
                    _(
                        "{font_start} Deleted {course_name} = {course_id} {location} {font_end}"
                    )
                ).format(
                    font_start=HTML("<font class='success'>"),
                    location=course.location,
                    course_id=course.id,
                    course_name=course.display_name,
                    font_end=HTML("</font>"),
                )

        context = self.get_context_data()
        context.update({"msg": message})
        return render(request, self.template_name, context)


@method_decorator(
    user_passes_test(
        user_has_access_to_users_panel, login_url="/404", redirect_field_name=None
    ),
    name="dispatch",
)
class UsersPanel(SysadminDashboardBaseView):
    """View to show the User Panel of SysAdmin."""

    template_name = "edx_sysadmin/users.html"

    def get_context_data(self, **kwargs):
        """
        Overriding get_context_data method to add custom fields
        """
        context = super().get_context_data(**kwargs)
        initial_data = kwargs.pop("initial_data", None)
        extra_fields = get_registration_required_extra_fields_with_values()

        if not is_registration_api_functional():
            context["disclaimer"] = True

        context.update(
            {
                "user_registration_form": UserRegistrationForm(
                    initial_data, extra_fields=extra_fields
                ),
                "is_users_tab": True,
            }
        )
        return context

    def post(self, request, *args, **kwargs):  # pylint: disable=unused-argument
        """
        POST method for User registration
        """
        extra_fields = get_registration_required_extra_fields_with_values()
        form = UserRegistrationForm(request.POST, extra_fields=extra_fields)
        context = self.get_context_data(initial_data=request.POST, **kwargs)
        if form.is_valid():
            context.update(
                create_user_account(form.cleaned_data, request.build_absolute_uri)
            )
            if context.get("success_message"):
                success_message = context.get("success_message")
                context = self.get_context_data()
                context["success_message"] = success_message
        else:
            context["error_message"] = _(
                "Unable to create new account due to invalid data"
            )

        return render(request, self.template_name, context)


@method_decorator(
    user_passes_test(
        user_has_access_to_git_import_panel, login_url="/404", redirect_field_name=None
    ),
    name="dispatch",
)
class GitImport(SysadminDashboardBaseView):
    """
    This provide the view to load or update courses from github
    """

    template_name = "edx_sysadmin/gitimport.html"

    def get_context_data(self, **kwargs):
        """
        Overriding get_context_data method to add custom fields
        """
        context = super().get_context_data(**kwargs)
        context["is_git_import_tab"] = True
        return context

    def get_course_from_git(self, gitloc, branch):
        """This downloads and runs the checks for importing a course in git"""

        if not (
            gitloc.endswith(".git")
            or gitloc.startswith("http:")
            or gitloc.startswith("https:")

edx_sysadmin/templates/edx_sysadmin/base.html
{% extends "main_django.html" %}
{% load i18n static %}

{% block headextra %}
    <link rel="stylesheet" href="{% static 'edx_sysadmin/css/style.css' %}">
    <script type="text/javascript" src="{% static 'js/header/header.js' %}"></script>
{% endblock %}

{% block body %}
<section class="container">
    <div class="sysadmin-dashboard-wrapper">
        <section class="sysadmin-dashboard-content">
            <h1 class="main-heading">{% trans "Sysadmin Dashboard" %}</h1>
            <hr />
            <h2 class="instructor-nav">
                {% if show_users_tab %}
                    <a href="{% url 'sysadmin:users' %}" class="{% if is_users_tab %} active {% endif %}">{% trans "Users" %}</a>
                {% endif %}
                {% if show_courses_tab %}
                    <a href="{% url 'sysadmin:courses' %}" class="{% if is_courses_tab %} active {% endif %}"> {% trans "Courses" %} </a>
                {% endif %}
                {% if show_git_import_tab %}
                    <a href="{% url 'sysadmin:gitimport' %}" class="{% if is_git_import_tab %} active {% endif %}"> {% trans "Git Import" %} </a>
                {% endif %}
                {% if show_git_logs_tab %}
                    <a href="{% url 'sysadmin:gitlogs' %}" class="{% if is_git_logs_tab %} active {% endif %}"> {% trans "Git Logs" %} </a>
                {% endif %}
            </h2>
            <hr />
            {% block panel %}
            {% endblock panel %}
        </section>
        {% block msg %}
        {% endblock msg %}
    </div>
</section>
{% endblock body %}

edx_sysadmin/templates/edx_sysadmin/courses.html
{% extends 'edx_sysadmin/base.html' %}

{% load i18n static %}

{% block headextra %}
{{ block.super }}
    <script type="text/javascript" src="{% static 'edx_sysadmin/js/course.js' %}"></script>
{% endblock %}

{% block panel %}
    <h3>{% trans "Administer Courses" %}</h3><br/>
    <form name="action" method="POST">
        {% csrf_token %}
        <ul class="list-input">
            <li class="field text">
            <label for="course_id">
                {% trans "Course ID or dir" %} :
            </label>
            <input type="text" name="course_id" style="width:60%" required />
            </li>
        </ul>
        <div class="form-actions">
            <button type="submit" name="action" value="del_course">{% trans "Delete course" %}</button>
        </div>
    </form>
    <hr style="width:100%" />

    {% block msg %}
        {% if msg %}
            <p>{{msg}}</p>
        {% endif %}
    {% endblock msg %}
    {% if datatable %}
        <br/>
        <br/>
        <p>
        <hr width="100%">
        <h2>{{datatable.title}}</h2>
        <table class="stat_table courses_table">
            <tr>
                {% for column in datatable.header %}
                    <th>{{column}}</th>
                {% endfor %}
            </tr>
            {% for key, value in datatable.data.items %}
            <tr id="{{value.git_directory}}">
                <td>{{value.display_name}}</td>
                <td>{{value.course_id}}</td>
                <td></td>
                <td></td>
                <td></td>
                <td>
                    <button onClick="getCourseGitDetails(this, '{{datatable.api_url}}', '{{value.git_directory}}')">Load Details</button>
                </td>
            </tr>
            {% endfor %}
        </table>
        </p>
    {% endif %}
{% endblock panel %}

edx_sysadmin/templates/edx_sysadmin/gitimport.html
{% extends 'edx_sysadmin/base.html' %}

{% load i18n static %}

{% block panel %}
    <h3>{% trans "Administer Courses" %}</h3><br/>
    <form name="action" method="POST">
        {% csrf_token %}
        <ul class="list-input">
            <li class="field text">
                <label for="repo_location">
                    {# Translators: Repo is short for git repository or source of #}
                    {# courseware; see http://git-scm.com/about #}
                    {% trans "Repo Location" %}:
                </label>
                <input type="text" name="repo_location" style="width:60%" />
            </li>
            <li class="field text">
                <label for="repo_location">
                    {# Translators: Repo is short for git repository (http://git-scm.com/about) or source of #}
                    {# courseware and branch is a specific version within that repository #}
                    {% trans "Repo Branch (optional)" %}:
                </label>
                <input type="text" name="repo_branch" style="width:60%" />
            </li>
        </ul>
        <div class="form-actions">
            {# Translators: GitHub is a popular website for hosting code #}
            <button type="submit" name="action" value="add_course">
                {% trans "Load new course from GitHub" %}
            </button>
        </div>
    </form>
    <hr style="width:100%" />
{% endblock panel %}
{% block msg %}
    {% if msg %}
        <p>{{msg}}</p>
    {% endif %}
{% endblock msg %}

edx_sysadmin/templates/edx_sysadmin/gitlogs.html
{% extends 'edx_sysadmin/base.html' %}

{% load i18n static %}
{% load sysadmin_extras %}


{% block headextra %}
{{ block.super }}
<script>
    $(function() {
        $(".toggle-import-log").click(function(e) {
            var self = $(this);
            var id = self.data("import-log");
            $("#import-log-" + id).toggle({
                duration: 200
            });
            if (self.html() === "[ + ]") {
              self.html(edx.HtmlUtils.HTML("[ &#8722; ]").toString());
            } else {
                self.text("[ + ]");
            }
            e.preventDefault();
        });
    });
</script>
{% endblock headextra %}

{% block panel %}
    <form name="dashform" method="POST" action="${reverse('sysadmin')}">
        <input type="hidden" name="csrfmiddlewaretoken" value="${ csrf_token }">
        <input type="hidden" name="dash_mode" value="">
    </form>

    {# Translators: refers to http://git-scm.com/docs/git-log #}
    <h3>{% trans "Git Logs" %}</h3>

    {% if course_id is not None %}
        {# Translators: Git is a version-control system; see http://git-scm.com/about #}
        <h2>{% blocktrans %}Recent git load activity for {{ course_id }}{% endblocktrans %}</h2>
        {% if error_msg %}
            <h3>{% trans "Error" %}:</h3>
            <p>{{error_msg}}</p>
        {% endif %}
    {% endif %}

    {% if logs %}
        {% include 'edx_sysadmin/gitlogs_pagination.html' %}
        <table class="stat_table" width="100%">
            <thead>
                <tr>
                    <th width="15%">{% trans "Date" %}</th>
                    <th width="15%">{% trans "Course ID" %}</th>
                    {# Translators: Git is a version-control system; see http://git-scm.com/about #}
                    <th>{% trans "Git Action" %}</th>
                </tr>
            </thead>
            <tbody>
            {% for cil in logs %}
                <tr>
                    <td>{% change_time_display cil.created %}</td>
                    <td>
                    <a href="{% url 'sysadmin:gitlogs_detail' cil.course_id %}">
                        {{cil.course_id}}
                    </a>
                    </td>
                    <td>
                    {% if course_id is not None %}
                        <a class="toggle-import-log" data-import-log="{{forloop.counter0}}" href="#">[ + ]</a>
                    {% endif %}
                    {{cil.git_log}}
                    </td>
                </tr>
                {# Show the full log of the latest import if viewing logs for a specific course #}
                {% if course_id is not None %}
                <tr class="import-log" id="import-log-{{forloop.counter0}}">
                    <td colspan="3"><pre>{{cil.course_import_log}}</pre>
                    </td>
                </tr>
                {% endif %}
            {% endfor %}
            </tbody>
        </table>
        {% include 'edx_sysadmin/gitlogs_pagination.html' %}
    {% else %}
        <div class="page-status">
        {% if not course_id %}
            {# If viewing all logs there are no logs available, let the user know. #}
            {# Translators: git is a version-control system; see http://git-scm.com/about #}
            {% trans "No git import logs have been recorded." %}
        {% else %}
            {# If viewing a single course and there are no logs available, let the user know. #}
            {# Translators: git is a version-control system; see http://git-scm.com/about #}
            {% trans "No git import logs have been recorded for this course." %}
        {% endif %}
        </div>
    {% endif %}
{% endblock panel %}

edx_sysadmin/templates/edx_sysadmin/gitlogs_pagination.html
{% load i18n static %}

<div class="pagination">
    {% if logs.has_previous %}
        <span class="previous-page">
            <a href="?page={{ logs.previous_page_number }}">
                {% trans "previous" %}
            </a>
        </span>
    {% endif %}
    {% if logs.number and logs.paginator.num_pages  %}
        {% with page_number=logs.number total_pages=logs.paginator.num_pages %}
            {% blocktrans %}Page {{ page_number }} of {{ total_pages }}{% endblocktrans %}
        {% endwith %}
    {% endif %}
    {% if logs.has_next %}
        <span class="next-page">
            <a href="?page={{ logs.next_page_number }}">
                {% trans "next" %}
            </a>
        </span>
    {% endif %}
</div>

edx_sysadmin/templates/edx_sysadmin/users.html
{% extends 'edx_sysadmin/base.html' %}

{% load i18n static %}

{% block panel %}
    {% if disclaimer %}
		<div class="disclaimer">
            <b>{% trans "Disclaimer" %}</b>: {% trans "Account Registration API is not functional in your platform, User Account will be created through DB Models" %}<br>
            {% trans "To make it functional, set" %} <span>ALLOW_PUBLIC_ACCOUNT_CREATION</span> {% trans "to" %} <span>True</span> {% trans "and" %} <span>ENABLE_REQUIRE_THIRD_PARTY_AUTH</span> {% trans "to" %} <span>False</span>.
        </div>
        <hr>
    {% endif %}
    <h3>{% trans "Register Users" %}</h3><br/>

    {% if error_message %}

		<div class="error_message">{{error_message|safe}}</div>
    {% endif %}
    {% if success_message %}
        <div class="success_message">{{success_message|safe}}</div>
    {% endif %}

    <form name="action" method="POST">
        {% csrf_token %}
        <div class="form-user-registration">
            {{ user_registration_form.as_p }}
        </div>
        <div class="form-actions">
            <button type="submit" name="action" value="create_account">{% trans "Create Account" %}</button>
        </div>
    </form>
    <hr style="width:100%" />
{% endblock panel %}